# Generated by Django 6.0 on 2026-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice articolo (esattamente 5 caratteri)', max_length=5, unique=True)),
                ('descrizione', models.CharField(help_text="Descrizione breve dell'articolo", max_length=30)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Quantità disponibile in magazzino')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli di Inventario',
                'ordering': ['codice'],
            },
        ),
    ]
